### ISSUE TITLE
Hřebínek je naletován ze stejné strany, jako snímače

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFPROBE01#3]
Vertikální hřebínek je naletován tak, že jeho vývody jsou na stejnou stranu jako jsou snímače.  Vývody tak překáží v použití snímačů.

**Comment by kaklik** [comment]
Konektor jsem otočil na opačnou stranu, ale teď jsou v repozitáři špatně obrázky..

**Comment by ChroustJan** [comment]
@kaklik  jaké by tohle mělo mít řešení? Aby to šlo uzavřít.

**Comment by roman-dvorak** [comment]
Myslím, že celý problém aktuálně spočívá v renderech, které to mají vyfocené obráceně.  Ale vzhledem k tomu, že máme fotky, tak ty rendery klidně vyhodit.

**Comment by ChroustJan** [comment]
A to se to takto používat nebude? Protože takto máme i potisk na PCB. Odesíláme tyto sondy bez zapájení. Protože si dovedu představit, že to někdo muže použít i opačně.

**Comment by roman-dvorak** [comment]
aha, nezapájený hřebínek to řeši dost dobře :) Tak já tam o tom připíšu poznámku.

**Comment by ChroustJan** [comment]
![image](https://user-images.githubusercontent.com/9783606/108856798-b4bcc800-75ea-11eb-85d6-8048edc03753.png)

**Comment by roman-dvorak** [comment]
ok, takto bych to považoval za vyřešené.

**Comment by kaklik** [comment]
No jde o to, že je to zatím asi blbě v datech na PCB. Důsledkem jsou pak ty otočené rendery a špatný osazováky.  Začalo to tím že od @ChroustJan  přišly PCB s hřebínkem naletovaným blbě, takže pokud je už něčím zajištěno, že se to nebude opakovat (předpokládám že snad možná mým commitem výše), tak je to možné uzavřít.
