### ISSUE TITLE
Wrong version of schematics in README

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TFPROBE01#7]
README obsahuje nějaké staré PDF se schématem. Je potřeba zkontrolovat správnosti cest a jestli repozitář neobsahuje nějaké duplicity.

**Comment by kaklik** [comment]
Myslím si, že primární příčina tohoto stavu je [nefunční KiCAD workflow](https://github.com/ThunderFly-aerospace/TFPROBE01/actions).
